export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES"

export const RECEIVE_POSTS = "RECEIVE_POSTS"
export const POST_UPDATE_VOTE = "POST_UPDATE_VOTE"
export const POST_DELETE = "POST_DELETE"
export const POST_ADD_NEW = "POST_ADD_NEW"
export const POST_EDIT = "POST_EDIT"


export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS"
export const COMMENT_UPDATE_VOTE = "COMMENT_UPDATE_VOTE"
export const COMMENT_DELETE = "COMMENT_DELETE"
export const COMMENT_PARENT_DELETED = "COMMENT_PARENT_DELETED"
export const COMMENT_ADD_NEW = "COMMENT_ADD_NEW"
export const COMMENT_EDIT = "COMMENT_EDIT"


export const UPDATE_SETTINGS = "UPDATE_SETTINGS"